version: '3.8'

services:
  # NGINX service for SSL and reverse proxy
  nginx:
    image: nginx:1.26-alpine
    container_name: sleep-olympics-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - sleep-network

  # Certbot service for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: sleep-olympics-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - sleep-network

  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-olympics-api:latest
    container_name: sleep-olympics-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Only expose to internal network, not externally
    expose:
      - "5000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sleep-network

networks:
  sleep-network:
    driver: bridge

volumes:
  logs:
    driver: local