version: '3.8'

services:
  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-olympics-api:latest
    container_name: sleep-olympics-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "80:5000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - sleep-network

networks:
  sleep-network:
    driver: bridge

volumes:
  logs:
    driver: local